=== dipinbhandari/Cheersgiftstore/Code/catalog_20048435.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CheersGiftStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Giftstore">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" minOccurs="0" />
                            <xs:element name="Address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Street" type="xs:string" minOccurs="0" />
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="country" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Telephone_Number">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Personal_Number" minOccurs="0" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="Mobile-no:\+44-[0-9]{2}-[0-9]{4}-[0-9]{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Official_Number" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="Phone-no:\+44-[0-9]{2}-[0-9]{4}-[0-9]{4}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>

                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Email" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"> </xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Website-Address" type="xs:string" />
                            <xs:element name="Logo" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="GiftCards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Giftcard" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Seller">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="SellerID" use="required" fixed="DG892C" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Cost" type="xs:string" />
                                        <xs:element name="validity" type="xs:string" />
                                        <xs:element name="No_of_users">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="limits" type="xs:integer" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Discount_Voucher" minOccurs="0">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type" use="required" fixed="Percentage" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Code" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="GiftcardID" type="xs:integer" use="required" />
                                    <xs:attribute name="CardType" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="copyright" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dipinbhandari/Cheersgiftstore/Code/catalog_20048435.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_20048435.css"?>
<CheersGiftStore xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="
catalog_20048435.xsd" xmlns="">
 <!-- <DIPIN-BHANDARI-20048435😊😁> -->
    <Giftstore>
     <Name>💎CheersGiftStore</Name>
     <Address>
        <Street> Whitworth Street,</Street>
        <city>Manchester</city>
        <country>[United kingdom]</country>
     </Address>
     <Telephone_Number>
        <Personal_Number>Mobile-no:+44-79-7577-8880</Personal_Number>
        <Official_Number>Phone-no:+44-67-8577-7678</Official_Number>
     </Telephone_Number>
     <Email>www.cheersgiftstore@gmail.com</Email>
     <Website-Address>https://www.cheersgiftstore.com</Website-Address>
     <Logo></Logo>
</Giftstore>
    <!-- giftcard-1 -->
    <GiftCards>
    <Giftcard GiftcardID="877" CardType="Physical">
        <Seller SellerID="DG892C"> Nordstrom Gift Card </Seller>
        <Cost>Cost:	£49 </Cost>
        <validity>validity-1Months
        </validity>
        <No_of_users limits="13">Number of users:6</No_of_users>
        <Discount_Voucher type="Percentage">Discount:5%</Discount_Voucher>
        <Code>Code:567CD43S</Code>
    </Giftcard>
    <!-- giftcard-2 -->
    <Giftcard GiftcardID="987" CardType="Virtual">
        <Seller SellerID="DG892C"> Subway Gift Card</Seller>
        <Cost>Cost:	£150 </Cost>
        <validity>validity-3Months
    
        </validity>
        <No_of_users limits="10">Number of users:4</No_of_users>
        <Discount_Voucher type="Percentage">Discount:7%</Discount_Voucher>
        
        <Code>Code:876654DAC</Code>
    </Giftcard>
    <!-- giftcard-3 -->
<Giftcard GiftcardID="667" CardType="Virtual">
    <Seller SellerID="DG892C">Cinemark Gift Card</Seller>
    <Cost>Cost:	£200</Cost>
    <validity>validity- 4Months
        
    </validity>
    <No_of_users limits="10">Number of users:4</No_of_users>
    <Discount_Voucher type="Percentage">Discount:7%</Discount_Voucher>
    <Code>Code:87AC56FG4</Code>
</Giftcard>
<!-- giftcard-4 -->
<Giftcard GiftcardID="986" CardType="Physical">
    <Seller SellerID="DG892C"> Victorias Secret Gift Card	</Seller>
    <Cost>Cost:	£350 </Cost>
    <validity>
        validity-7Months
    </validity>
    <No_of_users limits="10">Number of users:4</No_of_users>
    <Discount_Voucher type="Percentage">Discount:7%</Discount_Voucher>
    <Code>Code:JK567DF45</Code>
</Giftcard>
<!-- giftcard-5 -->
<Giftcard GiftcardID="465" CardType="Virtual">
    <Seller SellerID="DG892C"> Costco Gift Card</Seller>
    <Cost>Cost:	£650 </Cost>
    <validity>validity-9 Months
        
    </validity>
    <No_of_users limits="7">Number of users:5</No_of_users>
    <Discount_Voucher type="Percentage">Discount:4%</Discount_Voucher>
    <Code>Code:DASF34565</Code>
</Giftcard>
<!-- giftcard-6 -->
<Giftcard GiftcardID="745" CardType="Physical">
    <Seller SellerID="DG892C"> Disney Gift Card</Seller>
    <Cost>Cost:	£800 </Cost>
    <validity>
        validity-12 Months
    </validity>
    <No_of_users limits="9">Number of users:7</No_of_users>
    <Discount_Voucher type="Percentage">Discount:7%</Discount_Voucher>
    <Code>Code:9875R3DAC</Code>
</Giftcard>

<copyright>
    All Rights are Reserved to © 💎 CheersGiftStore | DIPIN-BHANDARI-20048435😊😁|
</copyright>
</GiftCards>
</CheersGiftStore>
